name: sefertorah
description: "Flutter project to create a book of Torah"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  flutter_svg: ^2.0.9
  go_router: ^14.0.0
  flutter_graph_view: ^2.0.2+1
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_graph_view:
    path: /home/noach/Documentos/git/flutter_graph_view


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/icons/book.svg
    - assets/icons/calendar.svg
    - assets/icons/comunity.svg
    - assets/icons/home.svg

  fonts:
    - family: PoiretOne
      fonts:
        - asset: fonts/PoiretOne-Regular.ttf
    - family: Ruthie
      fonts:
        - asset: fonts/Ruthie-Regular.ttf
